global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aws-staging'
    environment: 'staging'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:

  # Money Transfer Application (Same EC2 instance)
  - job_name: 'money-transfer-staging'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['3.7.163.119:8080']
        labels:
          service: 'money-transfer'
          environment: 'staging'

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'ec2-staging'
          service: 'node-exporter'

  # AlertManager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
        labels:
          service: 'alertmanager'
